logging:
  level:
    com.eduardomanrique.fxvalidation: DEBUG

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
xx:
  cache:
    cache-names: instruments
    caffeine:
      spec: expireAfterAccess=20s