DROP TABLE CURRENCY;
CREATE TABLE CURRENCY (
  ISO_CODE  VARCHAR(3) PRIMARY KEY,
  NAME VARCHAR(100)
);

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (
  ID  INTEGER PRIMARY KEY,
  NAME VARCHAR(100),
  ACTIVE BOOLEAN
);